### ISSUE TITLE
n-queens plot solution not scaling

### ISSUE THREAD

**Issue by r98inver** [mathcoding/opt4ds#4]
In the N-Queens colab, the `PlotSolution()` function does not scale well with `n` because of the fixed crown fontsize, causing a crown to span over multiple squares for higher values of `n`. Replacing `fontsize=7*size` with `fontsize=56*size/n` does the job. 
Corrected code:

    chessboard = np.zeros((n, n))

    chessboard[1::2,0::2] = 1
    chessboard[0::2,1::2] = 1

    plt.figure(figsize=(size, size))
    plt.imshow(chessboard, cmap='binary')

    for i, j in x:
        if x[i,j]() > 0:
            plt.text(i-1, j-1, '♕', color='darkorange',
                     fontsize=56*size/n, fontweight='bold', ha='center', va='center')
    plt.xticks([])
    plt.yticks([])
    plt.show()

**Comment by stegua** [comment]
Thanks! You're right, I have fixed and merged the corresponding notebook.
Let me know if you have any other suggestions.
